version: "3"

services:
  parser:
    container_name: vk_geo_parser
    build:
      dockerfile: ./Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      clickhouse:
        condition: service_started
      db:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "manage_queries.py", "3"]
      interval: 30s
      timeout: 10s
      retries: 100